In [23]:
import pandas as pd

In [24]:
import matplotlib.pyplot as plt

In [25]:
import numpy as np

# Which is The Best Cat Breed?

The best cat breed, for me, would depend on a few factors; health, life expectancy, shedding, family friendly, and playfulness.

In [69]:
catbreeds_df = pd.read_csv(r'C:\Users\rhian\Downloads\catbreeds.csv')

## Health

In [71]:
catbreeds_df[catbreeds_df['general_health'] > 4]

,name,length,origin,min_life_expectancy,max_life_expectancy,min_weight,max_weight,family_friendly,shedding,general_health,playfulness,children_friendly,grooming,intelligence,other_pets_friendly
4,American Wirehair,Medium to large,United States,14,18,8.0,15,4,3,5,3,4,5,4,3
42,Pixie-Bob,20 to 24 inches,"Washington, USA",13,15,8.0,17,5,4,5,4,5,2,4,4
45,Savannah,"13 to 20 inches, not including tail",USA,17,20,8.0,20,4,3,5,5,4,4,5,5
51,Snowshoe,Medium to long,"Philadelphia, USA",14,19,7.0,12,5,3,5,5,5,5,5,4

## Shedding

In [72]:
catbreeds_df[catbreeds_df['shedding'] < 2]

,name,length,origin,min_life_expectancy,max_life_expectancy,min_weight,max_weight,family_friendly,shedding,general_health,playfulness,children_friendly,grooming,intelligence,other_pets_friendly
7,Asian,Medium,Great Britain,15,15,10.0,10,5,1,4,4,5,3,4,4
9,Bambino,Short,United States,9,15,4.0,9,4,1,3,4,4,2,3,3
13,Brazilian Shorthair,Medium to large,Brazil,14,20,10.0,22,4,1,3,4,5,4,4,4
20,Chausie,Large,Egypt,12,14,15.0,30,4,1,4,4,1,5,5,4
24,Devon Rex,15 to 18 inches,"Devon, England",9,15,5.0,10,5,1,1,4,5,5,4,4
25,Donskoy,Medium,Russia,12,15,6.0,15,4,1,3,4,4,2,4,4
32,Khao Manee,10 to 12 inches,Thailand,10,12,8.0,10,4,1,3,5,5,4,4,4
39,Oriental Bicolor,Medium,United States,8,12,8.0,12,4,1,3,4,5,4,4,3
41,Peterbald,Medium,Russia,12,15,6.0,10,5,1,3,4,4,2,3,4
47,Serengeti,Medium,United States,10,15,8.0,15,4,1,3,4,4,4,4,4
52,Sokoke,Medium,Kenya,9,15,6.0,10,4,1,3,4,5,4,4,4
54,Sphynx,13 to 15 inches,Canada,8,14,6.0,12,5,1,2,4,5,2,4,5
57,Toyger,Medium,United States,10,15,7.0,15,5,1,3,4,4,4,4,4
60,Ukrainian Levkoy,Medium,Russia,9,15,8.0,12,5,1,3,4,5,2,5,4

## Family Friendliness

In [74]:
catbreeds_df[catbreeds_df['family_friendly'] > 4]

,name,length,origin,min_life_expectancy,max_life_expectancy,min_weight,max_weight,family_friendly,shedding,general_health,playfulness,children_friendly,grooming,intelligence,other_pets_friendly
1,Aegean,Medium,Greece,9,10,7.0,10,5,3,4,4,5,4,4,3
7,Asian,Medium,Great Britain,15,15,10.0,10,5,1,4,4,5,3,4,4
8,Australian Mist,Medium,Australia,15,18,8.0,15,5,2,4,4,4,4,4,3
10,Bengal Cats,"17 to 22 inches, not including tail",USA,10,16,8.0,17,5,2,3,5,5,4,5,5
11,Birman,15 to 18 inches,Unknown,12,16,6.0,12,5,3,2,4,5,2,4,5
16,Burmese,15 to 18 inches,Burma and Thailand,10,16,8.0,12,5,2,2,4,5,5,5,4
21,Colorpoint Shorthair,Small to medium,England,12,17,5.0,10,5,2,2,5,4,4,4,4
22,Cornish Rex,Small,United Kingdom,11,15,6.0,10,5,2,3,5,5,5,4,5
24,Devon Rex,15 to 18 inches,"Devon, England",9,15,5.0,10,5,1,1,4,5,5,4,4
27,Foldex,Medium,"Quebec, Canada",12,15,5.0,14,5,3,4,4,5,3,4,4
30,Japanese Bobtail,Medium,China and Japan,9,15,6.0,10,5,3,4,5,5,4,4,5
31,Javanese,Small to medium,United States and Canada,10,15,5.0,10,5,3,2,4,4,4,4,4
41,Peterbald,Medium,Russia,12,15,6.0,10,5,1,3,4,4,2,3,4
42,Pixie-Bob,20 to 24 inches,"Washington, USA",13,15,8.0,17,5,4,5,4,5,2,4,4
43,Ragdoll Cats,"17 to 21 inches, not including tail","Riverside, California, USA",12,17,10.0,20,5,4,3,4,5,1,4,4
46,Scottish Fold,10 to 12 inches,"Tayside, Scotland",11,14,6.0,13,5,3,3,3,5,2,4,4
48,Siamese Cat,"15 to 20 inches, not including tail",Thailand,8,15,6.0,14,5,2,3,4,4,4,5,4
49,Siberian,17 to 25 inches,Russia,11,18,8.0,17,5,4,4,5,5,2,4,4
50,Singapura,Small,Singapore,11,15,4.0,7,5,2,4,4,4,4,5,4
51,Snowshoe,Medium to long,"Philadelphia, USA",14,19,7.0,12,5,3,5,5,5,5,5,4
53,Somali,11 to 14 inches,United States,11,16,6.0,10,5,4,2,5,5,3,5,5
54,Sphynx,13 to 15 inches,Canada,8,14,6.0,12,5,1,2,4,5,2,4,5
56,Tonkinese,12 to 15 inches,United States and Thailand,10,16,6.0,12,5,2,2,5,5,4,5,4
57,Toyger,Medium,United States,10,15,7.0,15,5,1,3,4,4,4,4,4
58,Turkish Angora,Medium,"Ankara, Turkey",12,18,5.0,9,5,2,3,5,3,4,4,3
60,Ukrainian Levkoy,Medium,Russia,9,15,8.0,12,5,1,3,4,5,2,5,4

## Playful

In [75]:
catbreeds_df[catbreeds_df['playfulness'] > 4]

,name,length,origin,min_life_expectancy,max_life_expectancy,min_weight,max_weight,family_friendly,shedding,general_health,playfulness,children_friendly,grooming,intelligence,other_pets_friendly
0,Abyssinian,12 to 16 inches,Southeast Asia,9,15,6.0,10,3,3,2,5,5,3,5,5
10,Bengal Cats,"17 to 22 inches, not including tail",USA,10,16,8.0,17,5,2,3,5,5,4,5,5
17,Burmilla,Medium,England,10,15,6.5,13,4,3,3,5,4,4,3,4
21,Colorpoint Shorthair,Small to medium,England,12,17,5.0,10,5,2,2,5,4,4,4,4
22,Cornish Rex,Small,United Kingdom,11,15,6.0,10,5,2,3,5,5,5,4,5
23,Cyprus,Medium,Cyprus,12,15,8.0,16,4,2,4,5,4,4,4,4
30,Japanese Bobtail,Medium,China and Japan,9,15,6.0,10,5,3,4,5,5,4,4,5
32,Khao Manee,10 to 12 inches,Thailand,10,12,8.0,10,4,1,3,5,5,4,4,4
45,Savannah,"13 to 20 inches, not including tail",USA,17,20,8.0,20,4,3,5,5,4,4,5,5
49,Siberian,17 to 25 inches,Russia,11,18,8.0,17,5,4,4,5,5,2,4,4
51,Snowshoe,Medium to long,"Philadelphia, USA",14,19,7.0,12,5,3,5,5,5,5,5,4
53,Somali,11 to 14 inches,United States,11,16,6.0,10,5,4,2,5,5,3,5,5
56,Tonkinese,12 to 15 inches,United States and Thailand,10,16,6.0,12,5,2,2,5,5,4,5,4
58,Turkish Angora,Medium,"Ankara, Turkey",12,18,5.0,9,5,2,3,5,3,4,4,3

In the lists above, there are 37 different cats. 17 appear at least twice.

The below data is the only cat that appears three times on the lists above.

In [78]:
specific_row = catbreeds_df.loc[51]
print(specific_row)

name                            Snowshoe
length                    Medium to long
origin                 Philadelphia, USA
min_life_expectancy                   14
max_life_expectancy                   19
min_weight                           7.0
max_weight                            12
family_friendly                        5
shedding                               3
general_health                         5
playfulness                            5
children_friendly                      5
grooming                               5
intelligence                           5
other_pets_friendly                    4
Name: 51, dtype: object

From the data above, the Snowshoe appears to be teh best cat based on my conditions. The snowshoes life expectancy avergaes out at 16.5.